//files_path = { title: "~title", text: "~text", tags: "~tags", url: "~url" },
var tipuesearch = {
  pages: [
  { title: "O  pacote mi.rtl", text: "", tags: "", url: "temp.html" },
{ title: "Projetos em construção", text: "", tags: "", url: "projetos_em_construcao.html" },
{ title: "Titulo de sua pesquisa", text: "", tags: "", url: "search.html" },
{ title: "Search Results", text: "", tags: "", url: "search_result.html" },
{ title: "Projetos em construção", text: "", tags: "", url: "pendencias.html" },
{ title: "Objetivo", text: "", tags: "", url: "objetivo.html" },
{ title: "Search Results", text: "", tags: "", url: "t2.html" },
{ title: "Page Title", text: "", tags: "", url: "t1.html" },
{ title: "Home - Blog.pssp.app.br - em permanente construção. 🚧", text: "", tags: "", url: "index.html" },
{ title: "Histórico das ocorrência do Blog ", text: "", tags: "", url: "historico.html" },
{ title: "", text: "", tags: "", url: "temp_xquery.html" },
{ title: "Home - Blog.pssp.app.br - em permanente construção. 🚧", text: "", tags: "", url: "tipue_results.html" },
{ title: "Reflexão sobre fake, fatos e opinião", text: "", tags: "", url: "linguas_humanas/portugues/producao_de_textos/fake_fato_opiniao.html" },
{ title: "Estudo da língua portuguesa", text: "", tags: "", url: "linguas_humanas/portugues/producao_de_textos/descricao_de_textos.html" },
{ title: "Página de anotações de tudo que estudei sobre a língua portuguesa a partir de 28/11/2020", text: "", tags: "", url: "linguas_humanas/portugues/producao_de_textos/index.html" },
{ title: "", text: "", tags: "", url: "js/all.html" },
{ title: "sobre", text: "", tags: "", url: "js/footer.html" },
{ title: "Este arquivo é usado para editar o arquivo title.inc", text: "", tags: "", url: "js/title.html" },
{ title: "", text: "", tags: "", url: "templates/estudo/menuresponsive.html" },
{ title: "Minhas anotações que fiz ao estudar programação da linguagem css", text: "", tags: "", url: "templates/estudo/treeview_xhtml_ol.html" },
{ title: "Minhas anotações que fiz ao estudar programação da linguagem css", text: "", tags: "", url: "templates/estudo/functionseta.html" },
{ title: "Minhas anotações que fiz ao estudar programação da linguagem css", text: "", tags: "", url: "templates/estudo/treeview_xhtml_ul.html" },
{ title: "Minhas anotações que fiz ao estudar programação da linguagem css", text: "", tags: "", url: "templates/estudo/tgeneric.html" },
{ title: "Modelo 03 de documento markdown ", text: "", tags: "", url: "templates/markdown/modelo03.html" },
{ title: "Modelo de documento markdown ", text: "", tags: "", url: "templates/markdown/modelo02.html" },
{ title: "MODELO DE DOCUMENTO MARKDOWN DB ", text: "", tags: "", url: "templates/markdown/modelo01.html" },
{ title: "", text: "", tags: "", url: "templates/ejs/stork-config-toml/views/pages/example.html" },
{ title: "O que é linguagem shellscript ", text: "", tags: "", url: "programacao/shellscript/o_que_e_shellscript.html" },
{ title: "O que é Pascal ", text: "", tags: "", url: "programacao/pascal/o_que_e_pascal.html" },
{ title: "teste markdown", text: "", tags: "", url: "programacao/pascal/mermaid_graph_td.html" },
{ title: "teste.md", text: "", tags: "", url: "programacao/pascal/teste.html" },
{ title: "O que é IDE Lazarus ", text: "", tags: "", url: "programacao/pascal/lazarus/o_que_e_lazarus.html" },
{ title: "O que é fcl_web ", text: "", tags: "", url: "programacao/pascal/lazarus/O_que_e_fcl_web.html" },
{ title: "Como free pascal implementa multiplataforma ", text: "", tags: "", url: "programacao/pascal/lazarus/como_free_pascal_implementa_multiplataforma.html" },
{ title: "Como criar projetos free pascal multiplataforma ", text: "", tags: "", url: "programacao/pascal/lazarus/como_criar_projetos_free_pascal_multiplataforma.html" },
{ title: "Hierarquia de Classes", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/ClassHierarchy.html" },
{ title: "Todas as Units", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/AllUnits.html" },
{ title: "Todas as Classes, Interfaces, Objetos e Registros", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/AllClasses.html" },
{ title: "Todos os Tipos", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/AllTypes.html" },
{ title: "Legenda", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/legend.html" },
{ title: "Todos os Identificadores", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/AllIdentifiers.html" },
{ title: "Todas as Variáveis", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/AllVariables.html" },
{ title: "Todas as Units", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/index.html" },
{ title: "AppStrok", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/AppStrok.html" },
{ title: "Search Results", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/tipue_results.html" },
{ title: "Todas as Constantes", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/AllConstants.html" },
{ title: "Todas as funções e procedimentos", text: "", tags: "", url: "programacao/pascal/lazarus/stork/docs/AllFunctions.html" },
{ title: "", text: "", tags: "", url: "programacao/pascal/lazarus/fcl-web/fptemplate/README.html" },
{ title: "", text: "", tags: "", url: "programacao/pascal/lazarus/fcl-web/fptemplate/fptemplate.html" },
{ title: "", text: "", tags: "", url: "programacao/pascal/lazarus/fcl-web/examples/simpleserver/index.html" },
{ title: "Como instalar LAMW Manager no linux", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/Instalar_lamw_manager.html" },
{ title: "Copying to a temporary location", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/mensagens_ao_instalar_lamw4linux.html" },
{ title: "Como instalar e configurar LamW", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/instalar_configurar_lamw.html" },
{ title: "Tutorial: How to get your 'signed' release Apk: 'AppLAMWProject1'", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/doc_oficial/How_To_Get_Your_Signed_Release_Apk.html" },
{ title: "GUI Design WYSIWYG", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/doc_oficial/GUIDesignWYSIWYG.html" },
{ title: "Posts: 1229", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/doc_oficial/building-multi-arch-apk-using-gradle.html" },
{ title: "LAMW lifecycle for Android activity", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/doc_oficial/LAMW_lifecycle_for_Android_activity.html" },
{ title: "How to add an online library to LAMW", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/doc_oficial/How_to_add_an_online_library_to_LAMW.html" },
{ title: "how to create new components", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/doc_oficial/how_to_create_new_components.html" },
{ title: "How to Sign apk or bundle using gradle by ADiV", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/doc_oficial/How to Sign apk or bundle using gradle by ADiV.html" },
{ title: "Hello World App", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/doc_oficial/AppHelloWorld.html" },
{ title: "Network File System (NFS)", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/doc_oficial/index.html" },
{ title: "Create Android Virtual Device (AVD)", text: "", tags: "", url: "programacao/pascal/lazarus/lamw/doc_oficial/How_test_Reinit_Activity_in_Android_ Emulator.html" },
{ title: "O que é o projeto pas2js ", text: "", tags: "", url: "programacao/pascal/lazarus/pas2js/o_que_e_pas2js.html" },
{ title: "Tudo sobre pacotes Delphi XE", text: "", tags: "", url: "programacao/pascal/delphi/pacotes_em_delphi.html" },
{ title: "O QUE É LINGUAGEM SQL ", text: "", tags: "", url: "programacao/sql/o_que_e_sql.html" },
{ title: "Linguagem SQL", text: "", tags: "", url: "programacao/sql/index.html" },
{ title: "Linguagem python", text: "", tags: "", url: "programacao/python/index.html" },
{ title: "o que é projeto pelican ", text: "", tags: "", url: "programacao/python/pelican/o_que_e_projeto_pelican.html" },
{ title: "O Deno é um runtime para aplicações server-side usando javascript e/ou typescript", text: "", tags: "", url: "programacao/deno/index.html" },
{ title: "O que é algorítimo ", text: "", tags: "", url: "programacao/algoritimos/o_que_e_algoritimo.html" },
{ title: "", text: "", tags: "", url: "programacao/nodejs/temp.html" },
{ title: "Teoria snippets do editor vscode ", text: "", tags: "", url: "programacao/nodejs/teoria_snippets.html" },
{ title: "**Teoria sobre o Framework npm** ", text: "", tags: "", url: "programacao/nodejs/teoria_npm_js.html" },
{ title: "INSTALAR E CONFIGURAR O NODEJS ", text: "", tags: "", url: "programacao/nodejs/instalar.html" },
{ title: "CONFIGURAR O NODEJS ", text: "", tags: "", url: "programacao/nodejs/configurar.html" },
{ title: "Como usar funções assíncronas em javascript ", text: "", tags: "", url: "programacao/nodejs/functions_async.html" },
{ title: "Framework javascript para servidores web.", text: "", tags: "", url: "programacao/nodejs/index.html" },
{ title: "Histórico das ocorrência do estudo nodejs", text: "", tags: "", url: "programacao/nodejs/historico.html" },
{ title: "Teoria sobre o Framework nodejs ", text: "", tags: "", url: "programacao/nodejs/teoria_node_js.html" },
{ title: "Teoria do empacotador de módulos javascript webpack ", text: "", tags: "", url: "programacao/nodejs/teoria_webpack.html" },
{ title: "Objetivo do SqLite3 integrado ao nodejs", text: "", tags: "", url: "programacao/nodejs/sqlite3/objetivo.html" },
{ title: "O que é nvm ", text: "", tags: "", url: "programacao/nodejs/nvm/o_que_e_nvm.html" },
{ title: "Histório do teste express", text: "", tags: "", url: "programacao/nodejs/express/history.html" },
{ title: "Home - Blog.pssp.app.br", text: "", tags: "", url: "programacao/nodejs/express/test_express/home - blog.pssp.app.br.html" },
{ title: "Home - Blog.pssp.app.br", text: "", tags: "", url: "programacao/nodejs/express/test_express/test_express.html" },
{ title: "EXEMPLOS DE USO DO NODEJS", text: "", tags: "", url: "programacao/nodejs/express/test_express/index.html" },
{ title: "Home - Blog.pssp.app.br", text: "", tags: "", url: "programacao/nodejs/exemplos/home - blog.pssp.app.br.html" },
{ title: "Home - Blog.pssp.app.br", text: "", tags: "", url: "programacao/nodejs/exemplos/test_express.html" },
{ title: "", text: "", tags: "", url: "programacao/nodejs/exemplos/view-source_localhost_8080_blog.pssp.app.br.html" },
{ title: "", text: "", tags: "", url: "programacao/nodejs/exemplos/bootstrap.html" },
{ title: "EXEMPLOS DE USO DO NODEJS", text: "", tags: "", url: "programacao/nodejs/exemplos/index.html" },
{ title: "O que é templates ejs", text: "", tags: "", url: "programacao/nodejs/ejs/o_que_e_ejs.html" },
{ title: "EJS Is Fun", text: "", tags: "", url: "programacao/nodejs/ejs/ejs-demo1/views/pages/about.html" },
{ title: "EJS Is Fun", text: "", tags: "", url: "programacao/nodejs/ejs/ejs-demo1/views/pages/index.html" },
{ title: "", text: "", tags: "", url: "programacao/nodejs/ejs/ejs-demo2/views/pages/example.html" },
{ title: "O que é o framework electron ", text: "", tags: "", url: "programacao/nodejs/electron/o_que_e_electron.html" },
{ title: "O que é vue framework ", text: "", tags: "", url: "programacao/nodejs/vue/o_que_e_vue.html" },
{ title: "Linguagem HTML", text: "", tags: "", url: "programacao/html/index.html" },
{ title: "Linguagem HTML", text: "", tags: "", url: "programacao/html/videos/testvideo.html" },
{ title: "Objetivo do Apache Cordova ", text: "", tags: "", url: "programacao/html/cordova/objetivo.html" },
{ title: "Modelo de documento markdown ", text: "", tags: "", url: "programacao/html/js/arrow_functions.html" },
{ title: "JAVASCRIPT - Funções assíncronas", text: "", tags: "", url: "programacao/html/js/function_async.html" },
{ title: "Linguagem javascript", text: "", tags: "", url: "programacao/html/js/index.html" },
{ title: "Federalist Search", text: "", tags: "", url: "programacao/html/js/stork/index.html" },
{ title: "O que é pacote de pesquisa de site stork ", text: "", tags: "", url: "programacao/html/js/stork/o_que_e_stork.html" },
{ title: "", text: "", tags: "", url: "programacao/html/js/stork/ejs/stork-config-toml/views/pages/example.html" },
{ title: "", text: "", tags: "", url: "programacao/html/js/jekyll-tipue-search-master/search.html" },
{ title: "INSTALAR E CONFIGURAR O FRAMEWORK ANGULARJS", text: "", tags: "", url: "programacao/html/js/angular/configuracao.html" },
{ title: "", text: "", tags: "", url: "programacao/html/js/angular/exemplo-01/index.html" },
{ title: "", text: "", tags: "", url: "programacao/html/js/angular/exemplo-02/todo.html" },
{ title: "Tipue Search, a jQuery Site Search Plugin", text: "", tags: "", url: "programacao/html/js/tipuesearch/tipuesearch/Tipue Search 7.1/index.html" },
{ title: "Tipue Search, a jQuery Site Search Plugin", text: "", tags: "", url: "programacao/html/js/tipuesearch/tipuesearch/Tipue Search 7.1/demo/index.html" },
{ title: "", text: "", tags: "", url: "programacao/html/js/Lista_pastas/lista_pastas.html" },
{ title: "O que é typescript ", text: "", tags: "", url: "programacao/html/typescript/o_que_e_typescript.html" },
{ title: "Framework LoopBack 4.0 ", text: "", tags: "", url: "programacao/html/typescript/loopback.4.html" },
{ title: "Como documentar um programa typescript com a sintaxe tsdoc ", text: "", tags: "", url: "programacao/html/typescript/tsdoc.html" },
{ title: "Como instalar typescript no vscode", text: "", tags: "", url: "programacao/html/typescript/instalar.html" },
{ title: "Exemplo de Calculadora com TypeScript ", text: "", tags: "", url: "programacao/html/typescript/Comandos_typescript_calculator.html" },
{ title: "Linguagem typeScript", text: "", tags: "", url: "programacao/html/typescript/index.html" },
{ title: "test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/modules.html" },
{ title: "test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/index.html" },
{ title: "IWidget | test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/interfaces/__menu_principal_do_aplicativo.iwidget.html" },
{ title: "MapBits | test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/enums/itms_global.mapbits.html" },
{ title: "Itms_Global | test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/classes/itms_global.itms_global-1.html" },
{ title: "BaseWidget | test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/classes/__classes_abstratas_para_ferramentas_visuais_.basewidget.html" },
{ title: "TNSComponent | test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/classes/nscomponent.tnscomponent.html" },
{ title: "nscomponent | test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/modules/nscomponent.html" },
{ title: "- Menu Principal do aplicativo | test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/modules/__menu_principal_do_aplicativo.html" },
{ title: "- Classes abstratas para ferramentas visuais. | test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/modules/__classes_abstratas_para_ferramentas_visuais_.html" },
{ title: "itms_Global | test01", text: "", tags: "", url: "programacao/html/typescript/test01/html/docs/modules/itms_global.html" },
{ title: "O que é Framework Angular ", text: "", tags: "", url: "programacao/html/typescript/angular/o_que_e_angular.html" },
{ title: "Como criar formulário de login no angular ", text: "", tags: "", url: "programacao/html/typescript/angular/como_criar_formulario_de_login_no_angular.html" },
{ title: "Como instalar typescript no vscode", text: "", tags: "", url: "programacao/html/typescript/exemplos/test02/Calculator1.html" },
{ title: "Exemplo de Calculadora com TypeScript ", text: "", tags: "", url: "programacao/html/typescript/exemplos/test02/Calculator.html" },
{ title: "Programa para criar projeto básico typescript versão: 0.2.0", text: "", tags: "", url: "programacao/html/typescript/webpack_typescript/modelo01/my-tsc-init-ver-0.2.0.html" },
{ title: "Passo a passo para criar um novo projeto typescript  ", text: "", tags: "", url: "programacao/html/typescript/webpack_typescript/modelo01/my-tsc-init.html" },
{ title: "Prática da Video aula Webpack & TypeScript ", text: "", tags: "", url: "programacao/html/typescript/webpack_typescript/video_aula_the_net_ninja/curso_webpack_typescript.html" },
{ title: "Pesquisa de Alunos da UFC", text: "", tags: "", url: "programacao/html/chatgpt/pesquisa.html" },
{ title: "Cadastro de Alunos da UFC", text: "", tags: "", url: "programacao/html/chatgpt/index.html" },
{ title: "Linguagem markdown", text: "", tags: "", url: "programacao/html/markdown/indexcomprimido.html" },
{ title: "Test da extensão [Markdown Shortcuts](https://marketplace.visualstudio.com/items?itemName=mdickin.markdown-shortcuts)", text: "", tags: "", url: "programacao/html/markdown/test_markdown_shortcuts.html" },
{ title: "This is a test of Markdown syntax", text: "", tags: "", url: "programacao/html/markdown/This is a test of Markdown syntax.html" },
{ title: "Exemplo de um arquivos markdown misturado com html", text: "", tags: "", url: "programacao/html/markdown/test.html" },
{ title: "Linguagem markdown", text: "", tags: "", url: "programacao/html/markdown/index.html" },
{ title: "LINGUAGEM DE MARCAÇÃO DE TEXTO MARKDOWN ", text: "", tags: "", url: "programacao/html/markdown/o_que_e_markdown.html" },
{ title: "Editores que reconhecem a linguagem Markdown ", text: "", tags: "", url: "programacao/html/markdown/editores_markdown.html" },
{ title: "teste diagrama", text: "", tags: "", url: "programacao/html/markdown/graphviz/teste_diagrama.html" },
{ title: "", text: "", tags: "", url: "programacao/html/exemplos/dialog.html" },
{ title: "", text: "", tags: "", url: "programacao/html/exemplos/como_criar_div_dinamicamente.html" },
{ title: "BARRA DE PESQUISA USANDO HTML E JAVASCRIPT", text: "", tags: "", url: "programacao/html/exemplos/pesquisa.html" },
{ title: "", text: "", tags: "", url: "programacao/html/exemplos/bloco de código.html" },
{ title: "FindTextInDocument", text: "", tags: "", url: "programacao/html/exemplos/FindTextInDocument/index.html" },
{ title: "Estudo da linguagem JSON", text: "", tags: "", url: "programacao/html/json/json.html" },
{ title: "Linguagem json", text: "", tags: "", url: "programacao/html/json/index.html" },
{ title: "Minhas anotações que fiz ao estudar programação da linguagem css", text: "", tags: "", url: "programacao/html/css/teste css.html" },
{ title: "CSS - Position", text: "", tags: "", url: "programacao/html/css/posisao.html" },
{ title: "Minhas anotações que fiz ao estudar programação da linguagem css", text: "", tags: "", url: "programacao/html/css/index_3_colunas.html" },
{ title: "Linguagem Cascading Style Sheets (CSS)", text: "", tags: "", url: "programacao/html/css/index.html" },
{ title: "", text: "", tags: "", url: "programacao/html/css/exemplos/the animation-iteration-count property.html" },
{ title: "Teste do componente fptemplate", text: "", tags: "", url: "programacao/html/css/exemplos/table.html" },
{ title: "", text: "", tags: "", url: "programacao/html/css/exemplos/formresponsive/exemplo02-modal.html" },
{ title: "", text: "", tags: "", url: "programacao/html/css/exemplos/formresponsive/exemplo01.html" },
{ title: "", text: "", tags: "", url: "programacao/html/css/exemplos/formresponsive/exemplo02_popup_form.html" },
{ title: "O que é DDD ", text: "", tags: "", url: "analise_de_sistemas/o_que_e_ddd.html" },
{ title: "CONTROLE DE QUALIDADE DA PISCINA", text: "", tags: "", url: "quimica/piscina/index.html" },
{ title: "Ignorando arquivos ao enviar para o repositório git ", text: "", tags: "", url: "infraestrutura/linux/git/ignorando_arquivos_ao_enviar_para_o_repositorio_git.html" },
{ title: "Como hospedar um site estático no github page ", text: "", tags: "", url: "infraestrutura/linux/git/como_hospedar_um _site_estatico_no_github_page.html" },
{ title: "Listando o status do repositório ", text: "", tags: "", url: "infraestrutura/linux/git/listando_o_status_do_repositorio.html" },
{ title: "Tudo sobre git remoto ", text: "", tags: "", url: "infraestrutura/linux/git/tudo_sobre_git_remote.html" },
{ title: "Desvantagem do git", text: "", tags: "", url: "infraestrutura/linux/git/desvantagens.html" },
{ title: "Como instalar cliente git no Linux Debian ou derivados ", text: "", tags: "", url: "infraestrutura/linux/git/como_instalar_cliente_git_no_linux.html" },
{ title: "Desfazendo commit executado anteriormente ", text: "", tags: "", url: "infraestrutura/linux/git/desfazendo_commit_executado_anteriormente.html" },
{ title: "Criando repositório git ", text: "", tags: "", url: "infraestrutura/linux/git/criando_repositorio_git.html" },
{ title: "Pre-requisitos para instalar o git", text: "", tags: "", url: "infraestrutura/linux/git/pre_requisitos.html" },
{ title: "COMO INSTALAR E CONFIGURAR UM SERVIDOR GIT REMOTO ", text: "", tags: "", url: "infraestrutura/linux/git/como_instalar_servidor_git.html" },
{ title: "Adicionando documento ao repositório ", text: "", tags: "", url: "infraestrutura/linux/git/adicionando_documento_ao_repositorio.html" },
{ title: "Objetivo do git", text: "", tags: "", url: "infraestrutura/linux/git/objetivo.html" },
{ title: "como_instalar_servidor_git", text: "", tags: "", url: "infraestrutura/linux/git/example32.html" },
{ title: "COMO INSTALAR E CONFIGURAR UM SERVIDOR GIT REMOTO ", text: "", tags: "", url: "infraestrutura/linux/git/test.html" },
{ title: "Git - Sistema de controle de versões distribuído.", text: "", tags: "", url: "infraestrutura/linux/git/index.html" },
{ title: "O que é git? ", text: "", tags: "", url: "infraestrutura/linux/git/o_que_e_git.html" },
{ title: "Configurando git para enviar para o github ", text: "", tags: "", url: "infraestrutura/linux/git/github/configurando_git_para_enviar_para_o_github.html" },
{ title: "Criando script para enviar as alterações para o github ", text: "", tags: "", url: "infraestrutura/linux/git/github/criando_script_para_enviar_as_alteracoes_para_o_github.html" },
{ title: "Clonando repositório do github ", text: "", tags: "", url: "infraestrutura/linux/git/github/clonando_repositorio_do_github.html" },
{ title: "O que é banco de dados sqLite", text: "", tags: "", url: "infraestrutura/linux/banco_de_dados/sqlite3/o_que_e_sqlite.html" },
{ title: "O que é banco de dados postgresql", text: "", tags: "", url: "infraestrutura/linux/banco_de_dados/posgresql/o_que_e_postgresql.html" },
{ title: "EXEMPLOS DE USO DO BANCO DE DADOS MARIADB ", text: "", tags: "", url: "infraestrutura/linux/banco_de_dados/mariadb/exemplos.html" },
{ title: "COMO INSTALAR DO BANCO DE DADOS MARIADB ", text: "", tags: "", url: "infraestrutura/linux/banco_de_dados/mariadb/instalar.html" },
{ title: "CONFIGURAÇÃO DO MARIADB", text: "", tags: "", url: "infraestrutura/linux/banco_de_dados/mariadb/configurarmariadb.html" },
{ title: "_CONFIGURAÇÃO DO MARIADB_", text: "", tags: "", url: "infraestrutura/linux/banco_de_dados/mariadb/configurar.html" },
{ title: "Banco de dados Mariadb", text: "", tags: "", url: "infraestrutura/linux/banco_de_dados/mariadb/index.html" },
{ title: "O QUE É MARIADB", text: "", tags: "", url: "infraestrutura/linux/banco_de_dados/mariadb/o_que_e_mariadb.html" },
{ title: "Banco de dados mysql no Linux ", text: "", tags: "", url: "infraestrutura/linux/banco_de_dados/mysql/teoria_mysql.html" },
{ title: "Comandos básico do Shell do Linux ", text: "", tags: "", url: "infraestrutura/linux/shell/comandos_basico.html" },
{ title: "Objetivo", text: "", tags: "", url: "infraestrutura/linux/shell/objetivo.html" },
{ title: "Linux shell", text: "", tags: "", url: "infraestrutura/linux/shell/index.html" },
{ title: "Comandos básico do Shell do Linux ", text: "", tags: "", url: "infraestrutura/linux/shell/comandos_basico-na nuvem.html" },
{ title: "Histórico das ocorrências da página ", text: "", tags: "", url: "infraestrutura/linux/shell/historico.html" },
{ title: "$bash (1) - página de manual do Linux", text: "", tags: "", url: "infraestrutura/linux/shell/shell_bash/index.html" },
{ title: "Desvantagens do serviço NFS", text: "", tags: "", url: "infraestrutura/linux/nfs/desvantagens.html" },
{ title: "Configurando as exportações NFS no servidor host", text: "", tags: "", url: "infraestrutura/linux/nfs/configurando_exportacoes_nfs_servidor_host.html" },
{ title: "Comandos básicos do dia a dia para manutenção do serviço NFS", text: "", tags: "", url: "infraestrutura/linux/nfs/comandos_basicos.html" },
{ title: "Pre-requisitos para instalar o serviço NFS", text: "", tags: "", url: "infraestrutura/linux/nfs/pre_requisitos.html" },
{ title: "Instalação do Serviço NFS", text: "", tags: "", url: "infraestrutura/linux/nfs/instalacao.html" },
{ title: "Objetivo do Serviço NFS", text: "", tags: "", url: "infraestrutura/linux/nfs/objetivo.html" },
{ title: "Criando os diretórios de compartilhamento no servidor host", text: "", tags: "", url: "infraestrutura/linux/nfs/criando_diretorios_compartilhamento_host.html" },
{ title: "Network File System (NFS)", text: "", tags: "", url: "infraestrutura/linux/nfs/index.html" },
{ title: "Benefícios do serviço NFS", text: "", tags: "", url: "infraestrutura/linux/nfs/beneficios.html" },
{ title: "Como montar um dispositivo ou pasta ao iniciar o computador", text: "", tags: "", url: "infraestrutura/linux/nfs/montando_pastas_ao_iniciar_o_computador.html" },
{ title: "Montando pasta compartilhada do servidor na máquina cliente", text: "", tags: "", url: "infraestrutura/linux/nfs/montando_pasta_compartilhada_do_servidor_no_cliente.html" },
{ title: "[Um servidor de protocolo de área de trabalho remota de código aberto Xrdp](http://xrdp.org/) ", text: "", tags: "", url: "infraestrutura/linux/xrdp/teoria_xrdp.html" },
{ title: "Instruções de instalação para xrdp", text: "", tags: "", url: "infraestrutura/linux/xrdp/instalar_ultima_versao.html" },
{ title: "Este é um exemplo de como pode ser fácil escrever um documento para web.", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/temp.html" },
{ title: "Descrição dos arquivos de configuração do apache2 ", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/descricao_dos_arquivos_de_configuracao_do_apache2.html" },
{ title: "Desvantagens do Servidor Web Apache2", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/desvantagens.html" },
{ title: "Como usar Webmin para configurar apache2 ", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/como_usar_webmin_para_configurar_apache2.html" },
{ title: "**Exemplo de código usando a linguagem perl** ", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/teste_do_protocolo_cgi_usando_a_linguagem_perl.html" },
{ title: "**Teste do protocolo FastCGI usando a linguagem perl** ", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/teste_do_protocolo_fastcgi_usando_a_linguagem_perl.html" },
{ title: "Como criar vários sites na mesma máquina  ", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/como_criar_varios_sites.html" },
{ title: "Comandos mais usados na manutenção dos sites ", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/comandos_basicos.html" },
{ title: "Pre-requisito para instalar o servidor web apache2", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/pre_requisitos.html" },
{ title: "Objetivo do servidor web apache2", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/objetivo.html" },
{ title: "Servidor Web Service Apache2", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/index.html" },
{ title: "Benefícios que me levaram a estudar servidor web apache2.", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/beneficios.html" },
{ title: "Como instalar o Servidor Web Apache2 no Linux Debian ou seus derivados  ", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/Instalacao.html" },
{ title: "Teste do protocolo CGI usando a linguagem shell script ", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/teste_do_protocolo_cgi_usando_a_linguagem_shell_script.html" },
{ title: "Como configurar apache2 para executar CGI e FASTCGI  ", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/como_configurar_apache2_para_executar_cgi_e_fastcgi.html" },
{ title: "Como configurar apache2 para executar proxy reverso com balanceamento de carga ", text: "", tags: "", url: "infraestrutura/linux/servidor-web-apache/como_configurar_apache2_para_executar_prox_reverso_balanceamento_de_carga.html" },
{ title: "temo.html", text: "", tags: "", url: "infraestrutura/linux/flatpak/temo.html" },
{ title: "Dicas de como instalar e usar aplicativo no formato de distribuição flatpak nas distribuições debian.", text: "", tags: "", url: "infraestrutura/linux/flatpak/index.html" },
{ title: "", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/videos/Importar_as_Notas_Fiscais_de_Servico_para_o_fortes.html" },
{ title: "", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/videos/Baixar_as_Notas_Fiscais_de_Servico.html" },
{ title: "", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/videos/backup/Baixar_as_Notas_Fiscais_de_Servico.html" },
{ title: "QUANTO CUSTARÁ", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/quanto_custara.html" },
{ title: "QUANDO SERÁ FEITO", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/por_quem_sera_feito.html" },
{ title: "QUANTO CUSTARÁ", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/quanto_custa.html" },
{ title: "COMO SERÁ FEITO", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/como_sera_feito.html" },
{ title: "QUANDO SERÁ FEITO", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/quando_sera_feito.html" },
{ title: "O QUE SERÁ FEITO", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/o_que_sera_feito.html" },
{ title: "ONDE SERÁ FEITO", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/onde_sera_feito.html" },
{ title: "POR QUE SERÁ FEITO", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/por_que_sera_feito.html" },
{ title: "PROJETO DOCUMENTAÇÃO DA SERVCONT", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/index.html" },
{ title: "DOCUMENTAÇÃO DO SERVIDOR 01", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/hardwares/Documentação_do_Servidor_01.html" },
{ title: "ATAS DE REUNIÕES", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/atas/index.html" },
{ title: "REUNIÃO PARA DEFINIR AS TAREFAS DO **SETOR FISCAL**", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/markdown/atas/20221010_ata_de_reuniao.html" },
{ title: "uAnalise5w2h", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/uAnalise5w2h.html" },
{ title: "Hierarquia de Classes", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/ClassHierarchy.html" },
{ title: "Todas as Units", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/AllUnits.html" },
{ title: "Todas as Classes, Interfaces, Objetos e Registros", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/AllClasses.html" },
{ title: "Todos os Tipos", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/AllTypes.html" },
{ title: "Legenda", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/legend.html" },
{ title: "O QUE SERÁ FEITO", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/o_que_sera_feito.html" },
{ title: "Todos os Identificadores", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/AllIdentifiers.html" },
{ title: "uAnalise5w2h: Classe TAnalise5w2h", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/uAnalise5w2h.TAnalise5w2h.html" },
{ title: "uSetor_fiscal: Classe TFiscal_5W2H", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/uSetor_fiscal.TFiscal_5W2H.html" },
{ title: "Todas as Variáveis", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/AllVariables.html" },
{ title: "uSetor_fiscal", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/uSetor_fiscal.html" },
{ title: "Todas as Units", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/index.html" },
{ title: "Search Results", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/tipue_results.html" },
{ title: "Todas as Constantes", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/AllConstants.html" },
{ title: "Todas as funções e procedimentos", text: "", tags: "", url: "infraestrutura/servcont/5W2H/Docs/pasdoc/AllFunctions.html" },
{ title: "", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/videos/Importar_as_Notas_Fiscais_de_Servico_para_o_fortes.html" },
{ title: "", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/videos/Baixar_as_Notas_Fiscais_de_Servico.html" },
{ title: "", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/videos/backup/Baixar_as_Notas_Fiscais_de_Servico.html" },
{ title: "DOCUMENTAÇÃO DO SERVIDOR DE REDE 01", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/markdown/hardwares/Documentação_do_Servidor_de_Rede_01.html" },
{ title: "DOCUMENTAÇÃO DO SERVIDOR 01", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/markdown/hardwares/Documentação_do_Servidor_01.html" },
{ title: "uAnalise5w2h", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/uAnalise5w2h.html" },
{ title: "Hierarquia de Classes", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/ClassHierarchy.html" },
{ title: "Todas as Units", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/AllUnits.html" },
{ title: "Todas as Classes, Interfaces, Objetos e Registros", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/AllClasses.html" },
{ title: "Todos os Tipos", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/AllTypes.html" },
{ title: "Legenda", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/legend.html" },
{ title: "Todos os Identificadores", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/AllIdentifiers.html" },
{ title: "uAnalise5w2h: Classe TAnalise5w2h", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/uAnalise5w2h.TAnalise5w2h.html" },
{ title: "uSetor_fiscal: Classe TFiscal_5W2H", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/uSetor_fiscal.TFiscal_5W2H.html" },
{ title: "Todas as Variáveis", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/AllVariables.html" },
{ title: "uSetor_fiscal", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/uSetor_fiscal.html" },
{ title: "Todas as Units", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/index.html" },
{ title: "Search Results", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/tipue_results.html" },
{ title: "Todas as Constantes", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/AllConstants.html" },
{ title: "Todas as funções e procedimentos", text: "", tags: "", url: "infraestrutura/servcont/PasDoc/Docs/pasdoc/AllFunctions.html" },
{ title: "INTRODUÇÃO", text: "", tags: "", url: "infraestrutura/servcont/html/introducao.html" },
{ title: "MANUAL DOS SERVIÇOS DE CONTABILIDADE (Baseado na planilha [Empresas/Serviços](https://docs.google.com/spreadsheets/d/1xGE_pFJ_w8pQmJfeICaVQ9wUDRCxCzMcu6k1Ld6bC9w/edit?usp=sharing))", text: "", tags: "", url: "infraestrutura/servcont/html/index.html" },
{ title: "NOME DA TAREFA", text: "", tags: "", url: "infraestrutura/servcont/html/templates/modelo 5w2h.html" },
{ title: "DOCUMENTAÇÃO DO SERVIDOR 01", text: "", tags: "", url: "infraestrutura/servcont/html/hardwares/Documentação_do_Servidor_01.html" },
{ title: "Imposto Sobre Circulação de Mercadorias e Serviços (ICMS)", text: "", tags: "", url: "infraestrutura/servcont/html/obrigacoes_principais/impostos/estadual/icms.html" },
{ title: "Imposto Sobre Serviços (ISS)", text: "", tags: "", url: "infraestrutura/servcont/html/obrigacoes_principais/impostos/municipal/iss.html" },
{ title: "ATAS DE REUNIÕES", text: "", tags: "", url: "infraestrutura/servcont/html/atas/index.html" },
{ title: "REUNIÃO PARA DEFINIR AS TAREFAS DO **SETOR FISCAL**", text: "", tags: "", url: "infraestrutura/servcont/html/atas/20221010_ata_de_reuniao.html" },
{ title: "Software Sistema Empresa de Recolhimento do FGTS e Informações à Previdência Social (SEFIP)", text: "", tags: "", url: "infraestrutura/servcont/html/obrigacoes_acessorias/mensal/federal/folha_de_pagamento/sefip.html" },
{ title: "Requisitos para que o site Conectividade Social ICP V2 funcione no Windows", text: "", tags: "", url: "infraestrutura/servcont/html/obrigacoes_acessorias/mensal/federal/folha_de_pagamento/sefip/Requisitos_para_que_o_site_conectividade_social_icpv2_funcione.html" },
{ title: "Passo a passo para  cadastrar máquina na Conectividade Social ICP V2", text: "", tags: "", url: "infraestrutura/servcont/html/obrigacoes_acessorias/mensal/federal/folha_de_pagamento/sefip/passo_a_passo_para_cadastrar_maquina_no_site_conectividade_social_icpv2.html" },
{ title: "DCTF Web", text: "", tags: "", url: "infraestrutura/servcont/html/obrigacoes_acessorias/mensal/federal/fiscal/dctf_web.html" },
{ title: "ROTINAS DA SERVCONT", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/index.html" },
{ title: "SETOR PESSOAL SERVCONT", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_pessoal/index.html" },
{ title: "SETOR SOCIETÁRIO SERVCONT", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_societario/index.html" },
{ title: "GESTÃO SERVCONT", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/gestao/index.html" },
{ title: "DOCUMENTAÇÃO DO SERVIDOR DE REDE 01", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/gestao/ti/Documentação_do_Servidor_de_Rede_01.html" },
{ title: "SETOR DE TI SERVCONT", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/gestao/ti/index.html" },
{ title: "DOCUMENTAÇÃO DO SERVIDOR 01", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/gestao/ti/Documentação_do_Servidor_01.html" },
{ title: "REUNIÃO PARA DEFINIR AS TAREFAS DO **SETOR FISCAL**", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/gestao/atas/20221010 Ata de reunião.html" },
{ title: "ATAS DE REUNIÕES", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/gestao/atas/index.html" },
{ title: "SETOR FISCAL SERVCONT", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/index.html" },
{ title: "QUEBRA DE SEQUÊNCIAS", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/fazer_analise_dos_dados/quebra_de_sequencias.html" },
{ title: "FAZER ANÁLISE DOS DADOS - INDEX", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/fazer_analise_dos_dados/index.html" },
{ title: "COMPARATIVOS / CARTÕES DE CRÉDITOS E DÉBITOS", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/fazer_analise_dos_dados/comparativos/cartoes_de_creditos_e_debitos.html" },
{ title: "COMPARATIVOS / PIX", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/fazer_analise_dos_dados/comparativos/pix.html" },
{ title: "COMPARATIVOS", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/fazer_analise_dos_dados/comparativos/index.html" },
{ title: "COMPARATIVOS / VALORES", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/fazer_analise_dos_dados/comparativos/valor.html" },
{ title: "APURAÇÃO DOS TRIBUTOS", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/apuracao_dos_tributos/index.html" },
{ title: "APURAÇÃO DOS TRIBUTOS / CONTRIBUIÇÕES", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/apuracao_dos_tributos/contribuicoes/index.html" },
{ title: "APURAÇÃO DO IMPOSTO ISS", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/apuracao_dos_tributos/impostos/iss.html" },
{ title: "[APURAÇÃO DOS TRIBUTOS / IMPOSTOS](https://pt.wikipedia.org/wiki/Imposto)", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/apuracao_dos_tributos/impostos/index.html" },
{ title: "ESCRITURAR ISS", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/escriturar/iss.html" },
{ title: "INDEX - ESCRITURAR", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/escriturar/index.html" },
{ title: "ESCRITURAR ICMS/IPI", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_fiscal/escriturar/icms_e_ipi.html" },
{ title: "SETOR CONTÁBIL SERVCONT", text: "", tags: "", url: "infraestrutura/servcont/html.Versao.por.setores/setor_contabil/index.html" },
{ title: "Modelo 03 de documento markdown ", text: "", tags: "", url: "infraestrutura/androide/O_que_e_android_studio.html" },
{ title: "Pedir a Deus que me dê uma forma de sobreviver em uma atividade que me dê prazer", text: "", tags: "", url: "comportamentos/habitos/2022/Pedir a Deus que me dê uma forma de sobreviver em uma atividade que me de prazer.html" },
{ title: "Cinco Dicas do filme 'O poder além da vida' ", text: "", tags: "", url: "comportamentos/habitos/2022/Cinco_dicas_do_filme_o_poder_alem_da_vida.html" },
{ title: "As Janelas da Memória", text: "", tags: "", url: "comportamentos/habitos/2022/janelas_da_memoria.html" },
{ title: "Cinco Dicas Para Relacionamentos Saudáveis | Momentos Cury", text: "", tags: "", url: "comportamentos/habitos/2022/Cinco_dicas_para_relacionamentos_saudaveis.html" },
{ title: "Hábitos que desejo adquirir em 2021 Versão: 1.1 - Data: 10/01/2021", text: "", tags: "", url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.0.html" },
{ title: "Hábitos que desejo adquirir em 2021 Versão: 1.5 - Data: 27/01/2021", text: "", tags: "", url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.5.html" },
{ title: "Hábitos que desejo adquirir em 2021 Versão: 0.2", text: "", tags: "", url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_0.2.html" },
{ title: "Hábitos que desejo adquirir em 2021 Versão: 1.3 - Data: 19/01/2021", text: "", tags: "", url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.3.html" },
{ title: "Hábitos que desejo adquirir em 2021 Versão: 1.4 - Data: 27/01/2021", text: "", tags: "", url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.4.html" },
{ title: "Hábitos que desejo adquirir em 2021 Versão: 1.2 - Data: 12/01/2021", text: "", tags: "", url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.2.html" },
{ title: "**Hábitos que desejo adquirir em 2021 Versão: 1.6.3 - Data: 29/05/2021**", text: "", tags: "", url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.6.3.html" },
{ title: "**Hábitos que desejo adquirir em 2021 Versão: 1.6.2 - Data: 21/03/2021**", text: "", tags: "", url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.6.2.html" },
{ title: "MULHER HEREMITA", text: "", tags: "", url: "comportamentos/poemas/mulher_eremita.html" },
{ title: "Estudo do programa Anki ", text: "", tags: "", url: "comportamentos/anki/index.html" },
{ title: "**Manipulação psicológica (Manipulação psicológica)**", text: "", tags: "", url: "comportamentos/psicologia/diferenca_entre_manipular_e_influenciar.html" },
{ title: "As Janelas da Memória", text: "", tags: "", url: "comportamentos/psicologia/jamelas_da_memoria.html" },
{ title: "", text: "", tags: "", url: "test/test.html" },
{ title: "", text: "", tags: "", url: "test/menu_navbar.html" },
{ title: "Minhas crenças limitadoras em 2016", text: "", tags: "", url: "gestao_de_pessoas/crencas_limitadoras/2020-12-02-reflexão-minhas-crenças-limitadoras-em-2016.html" },
{ title: "Estudar qual a relação do aumento de pressão e diâmetro do cano", text: "", tags: "", url: "Hidraulica/estudo_relacao_aumento_ pressao_diametro_do_cano.html" },
{ title: "", text: "", tags: "", url: "css/sem uso/temp.html" },
{ title: "", text: "", tags: "", url: "css/sem uso/sidenav.html" },
{ title: "", text: "", tags: "", url: "css/sem uso/menuresponsive.html" },

  ],
};
