var tipuesearch = {
  pages: [
  {url: "Analise.html", title: "Análise do projeto ph.app.br", text: "", tags: "abrangentes acessar adequado adicionais adicional agenda ajudar análise aqui armazenar assistant atende atualização atualizados automatizadas baixar banco cadastros caso chamadas chave cliente clientes coletar como comunicar conectado confirmação confirmações consulta consultas contínua convênio convênios criar dados data datatime datatime_final detalhada dinheiro document document documentação eficiência e_mail enviar equipe espécie está estudar etapas expediente fazer final forma funcionamento garantir hora hora_inicial hospitais humanizados id_agenda id_cliente id_convênio id_medico id_médico id_operador id_operadores if_cliente implementar informações inicial integração interagir logar login mais manter manutenção matrícula medico médico médicos múltipla necessários nome número observações oferecer onde opção opcional openai operadores outras paciente para perguntas pesquisar plano pode podemos preços preparar prevista programa projeto próxima quais realizar responde rotinas saber secretária segurança senha sistema site sobre status telefone testes textos title todas treinamento usado usar utilizar utilize validação virtual whatsapp write " },
{url: "assistant_api_openai/index.html", title: "Assistant API da OpenAI ", text: "", tags: "2021 adquirir agregar após assunto atualizar baseado benefícios como compreensão concluído conhecimento conteúdo criar depois descreva descreve descrição deste desvantagens dificuldade document document documento encontrada encontradas escrever esse este estudado exemplo exemplos facilidade feito globais goback histórico index introdução modelo03 necessários objetivo objetivos oficial onclick para pode preciso principal produzi produzir referências requisitos resumo sacrificar semana site testar text title tópico write " },
{url: "database/index.html", title: "Banco de dados do projeto", text: "", tags: "agenda agendado ambas atender boolean cadastros caso class classdiagram cliente clientes código consulta conter convenio convênios criado datatime datatimefinal date deste devem diagrama document document email enderecodosite entidade entidades entre exemplo existir explicação gráfico haver hospitais hospital idagenda idcliente idconvenio identificador idmedico id_operador idoperador iguais igual indica indicar integer integracao integração interação lado login mais medico médico medicos menos mermaid mesmo mostra natureza nome obrigatório observacoes ocorrência opcional operador operadores outra paciente para pelo pode porque projeto referência referências relacionamento relações retorna senha serviços sido simbologia sistema status string tabela tabelas telefone tenha title #topo topo usada write " },
{url: "database/mapa_do_site.html", title: "Mapa do site", text: "", tags: "banco base cadastro clientes dados data document document printfooter projeto python script title write " },
{url: "mapa_do_site.html", title: "Mapa do site", text: "", tags: "análise assistant banco base cadastro clientes dados data database document document documento markdown modelo openai printfooter project projeto python script templates title write " },
{url: "readme.html", title: "project.ph.app.br", text: "", tags: "abordagens abrangentes acessar adequado adicionais adicional agenda agendamento agendar armazenar assistant atende atualização automatizadas banco bancos baseadas calendar cancelamento cancelar capaz caso chamadas coleta como confirmação confirmações consultas contínua convênios criar dados desenvolva desenvolver detalhada detalhes deve devem diálogo disponível document document documentação eficiência entender enviar equipe erros essas esta etapas fazer ferramentas firebase forma fornecidas funcionalidade funcionamento garantir google horário horários hospitais implementar incluir informações inicial integração integrar interação interações interage interativo isso mail manter manutenção médico médicos mysql natureza negociação negociar nome notificações nuvem objetivo oferecem oferecer onde openai outras paciente pacientes para partir pelo período pertinentes plano plataformas pode podem postgresql preços preferências preparar primeira primeiro processo projeto realizada realizar registradas registrar registro remarcação remarcar respectivas responder secretária seguinte segurança seguro semelhantes sheets sistema sistematizadas sobre soluções sugerir tecnologias telefone testes title todas treinamento twilio usando utilizando utilizar utilize validação virtual whatsapp write " },
{url: "templates/modelo01.html", title: "Modelo 01 de documento markdown ", text: "", tags: "2021 adquirir agregar após assunto atualizar baseado benefícios como compreensão concluído conhecimento conteúdo criar depois descreva descreve descrição deste desvantagens dificuldade document document documento encontrada encontradas escrever esse este estudado exemplo exemplos facilidade feito globais goback histórico index introdução modelo03 necessários objetivo objetivos oficial onclick para pode preciso principal produzi produzir referências requisitos resumo sacrificar semana site testar text title tópico write " }
  ]
};
