    <div class="tree-view">
      <ul class="tree-node">
        <li><input type="checkbox" id="Menu" /><label for="Menu" class="arrow">Menu</label>
          <ul>
            <li><input type="checkbox" id="Item01"  /> <label for="Item01">Item01</label></li>
            <li><input type="checkbox" id="Item02"  /> <label for="Item02">Item02</label></li>
            <li><input type="checkbox" id="SubMenu1"/> <label for="SubMenu1" class="arrow">SubMenu1</label>
              <ul>
                <li><input type="checkbox" id="Item01" /> <label for="Item01">Item01</label></li>
                <li><input type="checkbox" id="Item02" /> <label for="Item02">Item02</label></li>
                <li><input type="checkbox" id="Item03" /> <label for="Item03" >Item03</label></li>
                <li><input type="checkbox" id="Item04" /> <label for="Item04">Item04</label></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>